completed={0}が完了しました
system_error=予期せぬエラーが発生しました